name: Run Regression Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  regression-tests:
    runs-on: [make]
    # runs-on: [make, spike]
    strategy:
      matrix:
        test:
          - generic/test1
          - generic/test2
          - rv32i/test1
          - rv32i/test2
          - rv64i/test1
          - rv64i/test2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run test for ${{ matrix.test }}
        run: echo "make spike TEST=${{ matrix.test }}"
        # run: make spike TEST=${{ matrix.test }}


