name: Run Regression Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  discover-tests:
    runs-on: ubuntu-latest
    outputs:
      tests: ${{ steps.set-matrix.outputs.tests }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - id: set-matrix
        name: Discover tests
        run: |
          TEST_LIST=$(find generic rv32i rv64i -mindepth 1 -maxdepth 1 | jq -R . | jq -s .)
          echo "tests=${TEST_LIST}" >> $GITHUB_OUTPUT

  regression-tests:
    needs: discover-tests
    runs-on: [make]
    # runs-on: [make, spike]
    strategy:
      matrix:
        test: ${{ fromJson(needs.discover-tests.outputs.tests) }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: ${{ matrix.test }}
        run: echo "make spike TEST=${{ matrix.test }}"
        # run: make spike TEST=${{ matrix.test }}


