name: Run Regression Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  regression-tests:
    runs-on: [make, spike]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Regression Tests
        run: ./regression.sh

