name: Run Regression Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  regression-tests:
    runs-on: [make, spike]
    strategy:
      matrix:
        test:
          - rv32i/add.s
          - rv32i/addi.s

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run test for ${{ matrix.test }}
        run: make spike TEST=${{ matrix.test }}
        shell: bash

